### ISSUE TITLE
clice error

### ISSUE THREAD

**Issue by sgexzdkwse68792** [Kingfish404/segment-anything-webui#1]
<img width="650" alt="image" src="https://user-images.githubusercontent.com/117247286/230853992-3e98fdb7-5d9c-4403-bc96-5be248e17222.png">
error - src/pages/api/point.ts (32:21) @ handler
error - Error [ReferenceError]: FormData is not defined
    at handler (webpack-internal:///(api)/./src/pages/api/point.ts:45:22) {
  digest: undefined
}
  30 |     const filepath = file_list[0]['filepath']
  31 |     const readStream = await fs.readFile(filepath)
> 32 |     const req_data = new FormData()
     |                     ^
  33 |     const points = fields['points'][0] as string
  34 |     req_data.append('file', new Blob([readStream]), 'image')
  35 |     req_data.append('points', points)
error - src/pages/api/point.ts (32:21) @ handler
error - Error [ReferenceError]: FormData is not defined
    at handler (webpack-internal:///(api)/./src/pages/api/point.ts:45:22) {
  digest: undefined
}
  30 |     const filepath = file_list[0]['filepath']
  31 |     const readStream = await fs.readFile(filepath)
> 32 |     const req_data = new FormData()
     |                     ^
  33 |     const points = fields['points'][0] as string
  34 |     req_data.append('file', new Blob([readStream]), 'image')
  35 |     req_data.append('points', points)
error - src/pages/api/point.ts (32:21) @ handler
error - Error [ReferenceError]: FormData is not defined
    at handler (webpack-internal:///(api)/./src/pages/api/point.ts:45:22) {
  digest: undefined
}
  30 |     const filepath = file_list[0]['filepath']
  31 |     const readStream = await fs.readFile(filepath)
> 32 |     const req_data = new FormData()
     |                     ^
  33 |     const points = fields['points'][0] as string
  34 |     req_data.append('file', new Blob([readStream]), 'image')
  35 |     req_data.append('points', points)
error - src/pages/api/point.ts (32:21) @ handler
error - Error [ReferenceError]: FormData is not defined
    at handler (webpack-internal:///(api)/./src/pages/api/point.ts:45:22) {
  digest: undefined
}
  30 |     const filepath = file_list[0]['filepath']
  31 |     const readStream = await fs.readFile(filepath)
> 32 |     const req_data = new FormData()
     |                     ^
  33 |     const points = fields['points'][0] as string
  34 |     req_data.append('file', new Blob([readStream]), 'image')
  35 |     req_data.append('points', points)
error - src/pages/api/point.ts (32:21) @ handler
error - Error [ReferenceError]: FormData is not defined
    at handler (webpack-internal:///(api)/./src/pages/api/point.ts:45:22) {
  digest: undefined
}
  30 |     const filepath = file_list[0]['filepath']
  31 |     const readStream = await fs.readFile(filepath)
> 32 |     const req_data = new FormData()
     |                     ^
  33 |     const points = fields['points'][0] as string
  34 |     req_data.append('file', new Blob([readStream]), 'image')
  35 |     req_data.append('points', points)
wait  - compiling /api/everything (client and server)...
event - compiled successfully in 44 ms (50 modules)
error - src/pages/api/everything.ts (32:21) @ handler
error - Error [ReferenceError]: FormData is not defined
    at handler (webpack-internal:///(api)/./src/pages/api/everything.ts:45:22) {
  digest: undefined
}
  30 |     const filepath = file_list[0]['filepath']
  31 |     const readStream = await fs.readFile(filepath)
> 32 |     const req_data = new FormData()
     |                     ^
  33 |     req_data.append('file', new Blob([readStream]), 'image')
  34 |     const res_data = await fetch(
  35 |         API_URL + '/api/everything',
error - src/pages/api/point.ts (32:21) @ handler
error - Error [ReferenceError]: FormData is not defined
    at handler (webpack-internal:///(api)/./src/pages/api/point.ts:45:22) {
  digest: undefined
}
  30 |     const filepath = file_list[0]['filepath']
  31 |     const readStream = await fs.readFile(filepath)
> 32 |     const req_data = new FormData()
     |                     ^
  33 |     const points = fields['points'][0] as string
  34 |     req_data.append('file', new Blob([readStream]), 'image')
  35 |     req_data.append('points', points)
error - src/pages/api/point.ts (32:21) @ handler
error - Error [ReferenceError]: FormData is not defined
    at handler (webpack-internal:///(api)/./src/pages/api/point.ts:45:22) {
  digest: undefined
}
  30 |     const filepath = file_list[0]['filepath']
  31 |     const readStream = await fs.readFile(filepath)
> 32 |     const req_data = new FormData()
     |                     ^
  33 |     const points = fields['points'][0] as string
  34 |     req_data.append('file', new Blob([readStream]), 'image')
  35 |     req_data.append('points', points)
error - src/pages/api/point.ts (32:21) @ handler
error - Error [ReferenceError]: FormData is not defined
    at handler (webpack-internal:///(api)/./src/pages/api/point.ts:45:22) {
  digest: undefined
}
  30 |     const filepath = file_list[0]['filepath']
  31 |     const readStream = await fs.readFile(filepath)
> 32 |     const req_data = new FormData()
     |                     ^
  33 |     const points = fields['points'][0] as string
  34 |     req_data.append('file', new Blob([readStream]), 'image')
  35 |     req_data.append('points', points)
error - src/pages/api/point.ts (32:21) @ handler
error - Error [ReferenceError]: FormData is not defined
    at handler (webpack-internal:///(api)/./src/pages/api/point.ts:45:22) {
  digest: undefined
}
  30 |     const filepath = file_list[0]['filepath']
  31 |     const readStream = await fs.readFile(filepath)
> 32 |     const req_data = new FormData()
     |                     ^
  33 |     const points = fields['points'][0] as string
  34 |     req_data.append('file', new Blob([readStream]), 'image')
  35 |     req_data.append('points', points)
error - src/pages/api/point.ts (32:21) @ handler
error - Error [ReferenceError]: FormData is not defined
    at handler (webpack-internal:///(api)/./src/pages/api/point.ts:45:22) {
  digest: undefined
}
  30 |     const filepath = file_list[0]['filepath']
  31 |     const readStream = await fs.readFile(filepath)
> 32 |     const req_data = new FormData()
     |                     ^
  33 |     const points = fields['points'][0] as string
  34 |     req_data.append('file', new Blob([readStream]), 'image')
  35 |     req_data.append('points', points)
error - src/pages/api/point.ts (32:21) @ handler
error - Error [ReferenceError]: FormData is not defined
    at handler (webpack-internal:///(api)/./src/pages/api/point.ts:45:22) {
  digest: undefined
}
  30 |     const filepath = file_list[0]['filepath']
  31 |     const readStream = await fs.readFile(filepath)
> 32 |     const req_data = new FormData()
     |                     ^
  33 |     const points = fields['points'][0] as string
  34 |     req_data.append('file', new Blob([readStream]), 'image')
  35 |     req_data.append('points', points)
error - src/pages/api/point.ts (32:21) @ handler
error - Error [ReferenceError]: FormData is not defined
    at handler (webpack-internal:///(api)/./src/pages/api/point.ts:45:22) {
  digest: undefined
}
  30 |     const filepath = file_list[0]['filepath']
  31 |     const readStream = await fs.readFile(filepath)
> 32 |     const req_data = new FormData()
     |                     ^
  33 |     const points = fields['points'][0] as string
  34 |     req_data.append('file', new Blob([readStream]), 'image')
  35 |     req_data.append('points', points)
^C
❯ npm run dev

> segment-anything-webui@0.1.0 dev
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from /Users/jiangzhibin/workspace/openai/segment-anything-webui/.env.local
event - compiled client and server successfully in 594 ms (170 modules)
wait  - compiling...
event - compiled successfully in 49 ms (137 modules)

wait  - compiling / (client and server)...
event - compiled client and server successfully in 75 ms (177 modules)
wait  - compiling /api/point (client and server)...
event - compiled successfully in 37 ms (49 modules)
error - Error: options.maxTotalFileSize (1048576 bytes) exceeded, received 1096312 bytes of file data
    at Stream.<anonymous> (file:///Users/jiangzhibin/workspace/openai/segment-anything-webui/node_modules/formidable/src/Formidable.js:341:11)
    at Stream.emit (node:events:513:28)
    at MultipartParser.dataPropagation (file:///Users/jiangzhibin/workspace/openai/segment-anything-webui/node_modules/formidable/src/plugins/multipart.js:103:22)
    at MultipartParser.emit (node:events:525:35)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at MultipartParser.Readable.push (node:internal/streams/readable:228:10)
    at MultipartParser._handleCallback (file:///Users/jiangzhibin/workspace/openai/segment-anything-webui/node_modules/formidable/src/parsers/Multipart.js:97:10)
    at dataCallback (file:///Users/jiangzhibin/workspace/openai/segment-anything-webui/node_modules/formidable/src/parsers/Multipart.js:127:14)
    at MultipartParser._transform (file:///Users/jiangzhibin/workspace/openai/segment-anything-webui/node_modules/formidable/src/parsers/Multipart.js:320:5)
    at MultipartParser.Transform._write (node:internal/streams/transform:205:23)
    at writeOrBuffer (node:internal/streams/writable:391:12)
    at _write (node:internal/streams/writable:332:10)
    at MultipartParser.Writable.write (node:internal/streams/writable:336:10)
    at IncomingForm.write (file:///Users/jiangzhibin/workspace/openai/segment-anything-webui/node_modules/formidable/src/Formidable.js:254:18)
    at IncomingMessage.<anonymous> (file:///Users/jiangzhibin/workspace/openai/segment-anything-webui/node_modules/formidable/src/Formidable.js:202:16)
    at IncomingMessage.emit (node:events:513:28)
    at IncomingMessage.Readable.read (node:internal/streams/readable:527:10)
    at flow (node:internal/streams/readable:1011:34)
    at resume_ (node:internal/streams/readable:992:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  digest: undefined
}
wait  - compiling /_error (client and server)...
event - compiled client and server successfully in 57 ms (191 modules)
error - Error: options.maxTotalFileSize (1048576 bytes) exceeded, received 1097008 bytes of file data
    at Stream.<anonymous> (file:///Users/jiangzhibin/workspace/openai/segment-anything-webui/node_modules/formidable/src/Formidable.js:341:11)
    at Stream.emit (node:events:513:28)
    at MultipartParser.dataPropagation (file:///Users/jiangzhibin/workspace/openai/segment-anything-webui/node_modules/formidable/src/plugins/multipart.js:103:22)
    at MultipartParser.emit (node:events:525:35)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at MultipartParser.Readable.push (node:internal/streams/readable:228:10)
    at MultipartParser._handleCallback (file:///Users/jiangzhibin/workspace/openai/segment-anything-webui/node_modules/formidable/src/parsers/Multipart.js:97:10)
    at dataCallback (file:///Users/jiangzhibin/workspace/openai/segment-anything-webui/node_modules/formidable/src/parsers/Multipart.js:130:14)
    at MultipartParser._transform (file:///Users/jiangzhibin/workspace/openai/segment-anything-webui/node_modules/formidable/src/parsers/Multipart.js:252:17)
    at MultipartParser.Transform._write (node:internal/streams/transform:205:23)
    at writeOrBuffer (node:internal/streams/writable:391:12)
    at _write (node:internal/streams/writable:332:10)
    at MultipartParser.Writable.write (node:internal/streams/writable:336:10)
    at IncomingForm.write (file:///Users/jiangzhibin/workspace/openai/segment-anything-webui/node_modules/formidable/src/Formidable.js:254:18)
    at IncomingMessage.<anonymous> (file:///Users/jiangzhibin/workspace/openai/segment-anything-webui/node_modules/formidable/src/Formidable.js:202:16)
    at IncomingMessage.emit (node:events:513:28)
    at IncomingMessage.Readable.read (node:internal/streams/readable:527:10)
    at flow (node:internal/streams/readable:1011:34)
    at resume_ (node:internal/streams/readable:992:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  digest: undefined
}
error - Error: options.maxTotalFileSize (1048576 bytes) exceeded, received 1076229 bytes of file data
    at Stream.<anonymous> (file:///Users/jiangzhibin/workspace/openai/segment-anything-webui/node_modules/formidable/src/Formidable.js:341:11)
    at Stream.emit (node:events:513:28)
    at MultipartParser.dataPropagation (file:///Users/jiangzhibin/workspace/openai/segment-anything-webui/node_modules/formidable/src/plugins/multipart.js:103:22)
    at MultipartParser.emit (node:events:525:35)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at MultipartParser.Readable.push (node:internal/streams/readable:228:10)
    at MultipartParser._handleCallback (file:///Users/jiangzhibin/workspace/openai/segment-anything-webui/node_modules/formidable/src/parsers/Multipart.js:97:10)
    at dataCallback (file:///Users/jiangzhibin/workspace/openai/segment-anything-webui/node_modules/formidable/src/parsers/Multipart.js:130:14)
    at MultipartParser._transform (file:///Users/jiangzhibin/workspace/openai/segment-anything-webui/node_modules/formidable/src/parsers/Multipart.js:252:17)
    at MultipartParser.Transform._write (node:internal/streams/transform:205:23)
    at writeOrBuffer (node:internal/streams/writable:391:12)
    at _write (node:internal/streams/writable:332:10)
    at MultipartParser.Writable.write (node:internal/streams/writable:336:10)
    at IncomingForm.write (file:///Users/jiangzhibin/workspace/openai/segment-anything-webui/node_modules/formidable/src/Formidable.js:254:18)
    at IncomingMessage.<anonymous> (file:///Users/jiangzhibin/workspace/openai/segment-anything-webui/node_modules/formidable/src/Formidable.js:202:16)
    at IncomingMessage.emit (node:events:513:28)
    at IncomingMessage.Readable.read (node:internal/streams/readable:527:10)
    at flow (node:internal/streams/readable:1011:34)
    at resume_ (node:internal/streams/readable:992:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  digest: undefined
}

**Comment by Kingfish404** [comment]
FormData requires Node.js >=18, which is the current LTS version

- [Node.js](https://nodejs.org/en)
- [FormData - Web APIs | MDN](https://developer.mozilla.org/en-US/docs/Web/API/FormData)

**Comment by Kingfish404** [comment]
The env requirement has been added in README.md
